POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "nam",
  "password": "nam"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "ducanh",
  "password": "ducanh"
}

###
POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGQ1MzBjYmQ5ODQwZjAyNmMyZWZhZDkiLCJpYXQiOjE2MjQ3ODM5Nzh9.XV0Eh-cWYAnssJ96-cuUxdmL2ez6Z9A66IUnWWUTs7c

{
  "title": "react3",
  "description": "react3",
  "url": "react3.com",
  "status": "LEARNED"
}

###
GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGQ1MzBjYmQ5ODQwZjAyNmMyZWZhZDkiLCJpYXQiOjE2MjQ3ODM5Nzh9.XV0Eh-cWYAnssJ96-cuUxdmL2ez6Z9A66IUnWWUTs7c

###
PUT http://localhost:5000/api/posts/60d53cd245b4430f5481a652
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGQ1MzBjYmQ5ODQwZjAyNmMyZWZhZDkiLCJpYXQiOjE2MjQ2MDUzMzh9.p7egVBdWZ8Hx8mzSyafxUFnDM1qV0yzdBPMRa-Iynw4

{
  "title": "Vue",
  "description": "Vueeeee",
  "url": "vueeeeee.org",
  "status": "LEARNING"
}

###
DELETE http://localhost:5000/api/posts/60d53cd245b4430f5481a652
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGQ1MzBjYmQ5ODQwZjAyNmMyZWZhZDkiLCJpYXQiOjE2MjQ2MDUzMzh9.p7egVBdWZ8Hx8mzSyafxUFnDM1qV0yzdBPMRa-Iynw4
